### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by m1entus** [nowsecure/frida-cycript#4]
:frida-cycript m1entus$ make -j8
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
  CXX      libcycript_la-Scanner.lo
./Analyze Analysis.cpp g++ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fvisibility=hidden  -fobjc-exceptions -g -O2 -std=gnu++11 -Werror -Wno-deprecated-declarations -Wno-dangling-else -Wno-empty-body -Wno-overloaded-virtual -Wno-parentheses -Wno-tautological-undefined-compare -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -DCY_JAVA=1 -DCY_PYTHON=1 -DCY_OBJECTIVEC=1  >Bridge.def
cd Class; dx --dex --output=../Class/classes.dex *.class
/bin/sh: dx: command not found
make[4]: *** [Class/classes.dex] Error 127
make[4]: *** Waiting for unfinished jobs....
'dirent.h' file not found
cat ./Bridge.old >>Bridge.def
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by oleavr** [comment]
@m1entus (Sorry about the delay.) For now you will need the Android SDK on your PATH.
