### ISSUE TITLE
src/meson.build:168:2: ERROR: File cycript0.9 does not exist.

### ISSUE THREAD

**Issue by Einstein2150** [nowsecure/frida-cycript#44]
The command `meson build --buildtype minsize --strip` throws the error
`src/meson.build:168:2: ERROR: File cycript0.9 does not exist.`

I cloned the repository fresh from git and installed all the dependencies. Where is the problem? Because of the error ninja can't build it:

```ninja -C build
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory`
```

**Comment by lateralusd** [comment]
Apply the latch from [38](https://github.com/nowsecure/frida-cycript/pull/38)

**Comment by oleavr** [comment]
Sounds like the submodules might be missing. Try:

```
git submodule init
git submodule update
```

(Or clone again with `--recurse-submodules`.)

**Comment by Einstein2150** [comment]
> Apply the patch from [38](https://github.com/nowsecure/frida-cycript/pull/38)

this fixed it - thanks!

 Now ninja stucks because of data type problems:
```FAILED: src/node_modules 
/Applications/Xcode.app/Contents/Developer/usr/bin/python3 ../src/fetch-node-modules.py /usr/local/bin/npm ../src/package.json ../src/package-lock.json src
Traceback (most recent call last):
  File "../src/fetch-node-modules.py", line 19, in <module>
    sys.stderr.write(stdout_data)
TypeError: write() argument must be str, not bytes
[102/126] Compiling C++ object src/cycript.p/Console.cpp.o
ninja: build stopped: subcommand failed.```
