### ISSUE TITLE
I cannot compile this on 10.13

### ISSUE THREAD

**Issue by dapetcu21** [nowsecure/frida-cycript#9]
For once, this uses readline 6. Brew nowdays installs readline 7, so I had to compile readline on my own. 

Secondly, `BISON_PKGDATADIR=../ext/toolchain/usr/share/bison ../ext/toolchain/usr/bin/bison-macos-x86_64 -v --report=state -Werror -o Parser.cpp Parser.ypp` fails with `SIGABRT` and no additional details on my machine (macOS 10.13.4).

Thirdly, this seems to need a certain Java-related `dx` utility. I had no idea what to do about it, so I symlinked the one in Android SDK.

**Comment by oleavr** [comment]
Thanks for reporting! We have just replaced the build system with Meson, and are now building readline as a Meson subproject, which simplifies things.
